name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Images and run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code from GitHub
        uses: actions/checkout@v3

      - name: Debug Working Directory
        run: |
          pwd
          ls -R

      - name: Install Docker Compose Plugin
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose-plugin

      - name: Run end-to-end tests
        run: >
          docker compose -f docker-compose.yml 
          --profile testing up
          --build
          --exit-code-from test-service

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to DockerHub
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./web
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/page-tracker:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/page-tracker:latest
